### ISSUE TITLE
new rule proposal - use brace expansion

### ISSUE THREAD

**Issue by RafLeszczynski** [netguru/eslint-plugin-netguru-ember#10]
more details here:
https://github.com/DockYard/styleguides/blob/master/engineering/ember.md#use-brace-expansion

**Comment by RafLeszczynski** [comment]
@michalsnik I can work on this one during next weekend

**Comment by michalsnik** [comment]
Hi @RafLeszczynski, I just implemented rule for this, you can check it out here: #23

**Comment by RafLeszczynski** [comment]
@michalsnik I'll try to find some time today evening. Sore for being silent last couple of weeks. I'm just drowning in work and have no free time.

**Comment by michalsnik** [comment]
Sure, no problem I totally get it @RafLeszczynski

**Comment by michalsnik** [comment]
Version `v1.6.0` contains this rule
