### ISSUE TITLE
new rule proposal - do not use .on() in components

### ISSUE THREAD

**Issue by RafLeszczynski** [netguru/eslint-plugin-netguru-ember#11]
prevent using `.on()` in favour to component lifecycle hooks methods:

example:

BAD
```js
foo: on('init', () => {
  // ...
}),

bar: on('didInsertElement', () => {
  // ...
}),
```

GOOD
```js
init() {},
didInsertElement() {},
```

**Comment by RafLeszczynski** [comment]
@michalsnik I'll should have some free time this weekend so I'll take care of this one too.

**Comment by michalsnik** [comment]
`v1.1.0` contains new rule. Thanks @RafLeszczynski !
