### ISSUE TITLE
add unit tests to general and ember utils

### ISSUE THREAD

**Issue by RafLeszczynski** [netguru/eslint-plugin-netguru-ember#12]
I'd like to propose adding unit test to the helper methods:
https://github.com/netguru/eslint-plugin-netguru-ember/blob/master/rules/utils/ember.js
https://github.com/netguru/eslint-plugin-netguru-ember/blob/master/rules/utils/utils.js

Some of these helper methods have quite complex logic and it would be nice to cover it with tests. What to you think about it?

**Comment by michalsnik** [comment]
Absolutely @RafLeszczynski , I love this idea. Tests are always highly appreciated 👍 
It would also make the code easier to understand by just looking at unit tests instead of trying to understand the logic behind them. I'll try to prepare example test suit in my spare time.

**Comment by michalsnik** [comment]
I didn't had time last week to look at this, I'll probably work on this after 20.09.

**Comment by RafLeszczynski** [comment]
@michalsnik I see you're using `mocha`. Do you want to add some special assertion library for these tests or default node `assert` module is fine?

**Comment by michalsnik** [comment]
I'm willing to use Chai @RafLeszczynski

**Comment by RafLeszczynski** [comment]
@michalsnik OK, never used `chai` before so I'm more than happy to give it a try.

**Comment by michalsnik** [comment]
Hi @RafLeszczynski, I also had time to implement test suite for utils file today: #24 
Test for eslint utils will be in separate PR, if you'd like to play with chai, feel free to prepare PR in your spare time, but let me know before so we don't work on the same thing simultaneously.

**Comment by michalsnik** [comment]
Added in `v1.6.5`
