### ISSUE TITLE
Add support for eslint-rule-documentation

### ISSUE THREAD

**Issue by caseywatts** [netguru/eslint-plugin-netguru-ember#30]
(this issue is to track what I'm doing, I'm on it >:) )

eslint-rule-documentation makes it so you can click on a linter error (in Atom for instance) and it will take you to the rule your code is breaking. I've PR'd that repo with our predictable rule URL format:
`https://github.com/netguru/ember-styleguide#RULENAME`

https://github.com/jfmengels/eslint-rule-documentation/blob/master/contributing.md
https://github.com/jfmengels/eslint-rule-documentation/pull/5

**Comment by michalsnik** [comment]
Cool @caseywatts ! We were just about to perform the same thing :D Thanks for taking care of this! We appreciate it :)

**Comment by netes** [comment]
Hi @caseywatts!
First of all, thanks a lot for the effort! I'm actually working on this with a little bit different approach. I've already prepared a doc with all rules used in our plugin along with the descriptions which will be put in this repo, not in `ember-styleguide`. We want to keep these two separated for now - that way links to the rules will be consistent with our plugin name. In a few days (maybe even tomorrow) I'll create a PR for this.
Based on that I think we can close https://github.com/jfmengels/eslint-rule-documentation/pull/5 and I'll open a new one with proper URLs :)

**Comment by caseywatts** [comment]
Awesome! I was wondering about the repo difference lol

I closed the PR, I'll let you guys handle it :)

**Comment by netes** [comment]
Hi there @caseywatts!
I've made a PR with docs, so after merging it, I'll open PR in `eslint-rule-documentation` :)

**Comment by michalsnik** [comment]
Cool, I'm glad you guys agreed on this :)

I just reviewed @netes PR, and we'll merge this soon.

**Comment by netes** [comment]
https://github.com/jfmengels/eslint-rule-documentation/pull/7
So we can close this issue I think :)

**Comment by caseywatts** [comment]
🎉 🎉 🎉
