### ISSUE TITLE
`routes-segments-snake-case` fails for multiple dynamic segments

### ISSUE THREAD

**Issue by RafLeszczynski** [netguru/eslint-plugin-netguru-ember#6]
If the route has just one segment the rules work OK:

`this.route('route_name', { path: '/route_name/:segment_a' });`

But the rule throws error if the route has more than one dynamic segment:

`this.route('route_name', { path: '/route_name/:segment_a/:segment_b' });`

https://github.com/netguru/eslint-plugin-netguru-ember/blob/master/rules/routes-segments-snake-case.js#L31 returns only first segment with `/` at the and so the `isSnakeCase` returns false and other dynamic segments after first one are skipped.

Of course as usual I'm happy to make a PR just let me know that you are OK with introducing changes to this rule?

**Comment by michalsnik** [comment]
Hi @RafLeszczynski ,

You're right, this should also work for multiple dynamic segments. If you'd like feel free to prepare a PR. If not I or one of my friends will take care of this somewhere around upcoming week :)

**Comment by RafLeszczynski** [comment]
@michalsnik I have some free time today, so I'll try to fix this one. Expect PR soon

**Comment by RafLeszczynski** [comment]
PR: https://github.com/netguru/eslint-plugin-netguru-ember/pull/15

**Comment by michalsnik** [comment]
Thanks for providing a good solution 👍
