### ISSUE TITLE
new rule proposal - order in routes / controllers

### ISSUE THREAD

**Issue by RafLeszczynski** [netguru/eslint-plugin-netguru-ember#7]
We already have rules for checking order of properties inside components and ember-data models. What do you think about introducing rules for routes and controllers?

**Comment by michalsnik** [comment]
I'm starting to work on this.

**Comment by michalsnik** [comment]
Prepared here: #22 
Feel free to check it out @RafLeszczynski

**Comment by michalsnik** [comment]
It's done in `v1.5.0`.
