### ISSUE TITLE
new rule proposal - no objects and array as component default props

### ISSUE THREAD

**Issue by RafLeszczynski** [netguru/eslint-plugin-netguru-ember#8]
What do you think about introducing a rule to check for potential leaking state into components factories? 

The problem description can be find here:
https://dockyard.com/blog/2015/09/18/ember-best-practices-avoid-leaking-state-into-factories

**Comment by michalsnik** [comment]
Thanks for posting interesting proposals @RafLeszczynski,  these might be a good improvements to our style guide.

I'm going to discuss about all suggested proposal on our internal `Ember Meeting` and will be back around thursday with some feedback and our roadmap for further improvements :)

**Comment by RafLeszczynski** [comment]
@michalsnik any updates after your internal Ember Meeting?

**Comment by michalsnik** [comment]
Hi @RafLeszczynski 

We discussed everything on a meeting last week, and we agreed with all of your proposals. I'm setting proper labels now and it looks like we have a good roadmap to pursuit. Unfortunately I'm kind of busy lately after work, but hopefully someone will help us address all of these proposals. 

Thanks for great ideas, we really appreciate it! And as usual we're open to see new PRs :)

**Comment by RafLeszczynski** [comment]
@michalsnik I think I'll be able to prepare some PR in next couple of days.

**Comment by michalsnik** [comment]
@RafLeszczynski Let me know what rules are you actually working on. Just a quick note under specific issue would be great so that we don't duplicate each other ;)

**Comment by RafLeszczynski** [comment]
@michalsnik Ok so I'll leave this one to you. Check the PR comments for some feedback.

**Comment by michalsnik** [comment]
Thanks for a feedback, `v1.4.0` contains rule for this proposal.
