### ISSUE TITLE
new rule proposal - do not use Ember's function prototype extensions

### ISSUE THREAD

**Issue by RafLeszczynski** [netguru/eslint-plugin-netguru-ember#9]
Prevent from doing this:

```js
{
  propOne: function() {
    // function body
  }.property('propA', 'propB'),
  
  propTwo: function() {
    // function body
  }.observe('propC'),
}
```

Instead use regular `computed` and `observer`.

**Comment by RafLeszczynski** [comment]
@michalsnik I can take care of this one and hopefully prepare PR over weekend.

**Comment by michalsnik** [comment]
`eslint-plugin-netguru-ember@v1.1.0` contains this rule now.
It is also added in `eslint-config-netguru-ember@v1.2.0`
